// <auto-generated />
namespace Vocab
{
    /// <summary>XML Schema Vocabulary (http://www.w3.org/2001/XMLSchema#).</summary>
    /// <remarks>As seen on https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes</remarks>
    public static partial class Xsd
    {
        /// <summary>
        /// Vocabulary prefix
        /// </summary>
        /// <value>xsd</value>
        public static readonly string Prefix = "xsd";

        /// <summary>
        /// Vocabulary base URI
        /// </summary>
        /// <value>
        /// http://www.w3.org/2001/XMLSchema#
        /// </value>
        public static readonly string BaseUri = "http://www.w3.org/2001/XMLSchema#";

        /// <summary> Character strings (but not all Unicode character strings) </summary>
        public static readonly string @string = BaseUri + "string";

        /// <summary> true, false </summary>
        public static readonly string boolean = BaseUri + "boolean";

        /// <summary> Arbitrary-precision decimal numbers </summary>
        public static readonly string @decimal = BaseUri + "decimal";

        /// <summary> Arbitrary-size integer numbers </summary>
        public static readonly string integer = BaseUri + "integer";

        /// <summary> 64-bit floating point numbers incl. ±Inf, ±0, NaN </summary>
        public static readonly string @double = BaseUri + "double";

        /// <summary> 32-bit floating point numbers incl. ±Inf, ±0, NaN </summary>
        public static readonly string @float = BaseUri + "float";

        /// <summary> Dates (yyyy-mm-dd) with or without timezone </summary>
        public static readonly string date = BaseUri + "date";

        /// <summary> Times (hh:mm:ss.sss…) with or without timezone </summary>
        public static readonly string time = BaseUri + "time";

        /// <summary> Date and time with or without timezone </summary>
        public static readonly string dateTime = BaseUri + "dateTime";

        /// <summary> Date and time with required timezone </summary>
        public static readonly string dateTimeStamp = BaseUri + "dateTimeStamp";

        /// <summary> Gregorian calendar year </summary>
        public static readonly string gYear = BaseUri + "gYear";

        /// <summary> Gregorian calendar month </summary>
        public static readonly string gMonth = BaseUri + "gMonth";

        /// <summary> Gregorian calendar day of the month </summary>
        public static readonly string gDay = BaseUri + "gDay";

        /// <summary> Gregorian calendar year and month </summary>
        public static readonly string gYearMonth = BaseUri + "gYearMonth";

        /// <summary> Gregorian calendar month and day </summary>
        public static readonly string gMonthDay = BaseUri + "gMonthDay";

        /// <summary> Duration of time </summary>
        public static readonly string duration = BaseUri + "duration";

        /// <summary> Duration of time (months and years only) </summary>
        public static readonly string yearMonthDuration = BaseUri + "yearMonthDuration";

        /// <summary> Duration of time (days, hours, minutes, seconds only) </summary>
        public static readonly string dayTimeDuration = BaseUri + "dayTimeDuration";

        /// <summary> -128…+127 (8 bit) </summary>
        public static readonly string @byte = BaseUri + "byte";

        /// <summary> -32768…+32767 (16 bit) </summary>
        public static readonly string @short = BaseUri + "short";

        /// <summary> -2147483648…+2147483647 (32 bit) </summary>
        public static readonly string @int = BaseUri + "int";

        /// <summary> -9223372036854775808…+9223372036854775807 (64 bit) </summary>
        public static readonly string @long = BaseUri + "long";

        /// <summary> 0…255 (8 bit) </summary>
        public static readonly string unsignedByte = BaseUri + "unsignedByte";

        /// <summary> 0…65535 (16 bit) </summary>
        public static readonly string unsignedShort = BaseUri + "unsignedShort";

        /// <summary> 0…4294967295 (32 bit) </summary>
        public static readonly string unsignedInt = BaseUri + "unsignedInt";

        /// <summary> 0…18446744073709551615 (64 bit) </summary>
        public static readonly string unsignedLong = BaseUri + "unsignedLong";

        /// <summary> Integer numbers >0 </summary>
        public static readonly string positiveInteger = BaseUri + "positiveInteger";

        /// <summary> Integer numbers ≥0 </summary>
        public static readonly string nonNegativeInteger = BaseUri + "nonNegativeInteger";

        /// <summary> Integer numbers &lt;0 </summary>
        public static readonly string negativeInteger = BaseUri + "negativeInteger";

        /// <summary> Integer numbers ≤0 </summary>
        public static readonly string nonPositiveInteger = BaseUri + "nonPositiveInteger";

        /// <summary> Hex-encoded binary data </summary>
        public static readonly string hexBinary = BaseUri + "hexBinary";

        /// <summary> Base64-encoded binary data </summary>
        public static readonly string base64Binary = BaseUri + "base64Binary";

        /// <summary> Absolute or relative URIs and IRIs </summary>
        public static readonly string anyURI = BaseUri + "anyURI";

        /// <summary> Language tags per http://tools.ietf.org/html/bcp47 </summary>
        public static readonly string language = BaseUri + "language";

        /// <summary> Whitespace-normalized strings </summary>
        public static readonly string normalizedString = BaseUri + "normalizedString";

        /// <summary> Tokenized strings </summary>
        public static readonly string token = BaseUri + "token";

        /// <summary> XML NMTOKENs </summary>
        public static readonly string NMTOKEN = BaseUri + "NMTOKEN";

        /// <summary> XML Names </summary>
        public static readonly string Name = BaseUri + "Name";

        /// <summary> XML NCNames </summary>
        public static readonly string NCName = BaseUri + "NCName";

    }
}